#!/bin/bash
set -e

FILE_PATH=$(python3 -c "import sys,json; d=json.load(sys.stdin); print(d.get('tool_input',d).get('file_path',''))" 2>/dev/null)

[ -z "$FILE_PATH" ] && exit 0

# Block edits to auto-generated directories
if [[ "$FILE_PATH" == */.source/* ]] || [[ "$FILE_PATH" == */.source ]]; then
  echo '{"decision": "block", "reason": ".source/ is auto-generated by fumadocs-mdx. Never edit files there."}'
  exit 0
fi

if [[ "$FILE_PATH" == */content/docs/api/* ]] || [[ "$FILE_PATH" == */content/docs/api ]]; then
  echo '{"decision": "block", "reason": "content/docs/api/ is auto-generated from OpenAPI spec. Regenerate with: pnpm generate-api-docs"}'
  exit 0
fi

if [[ "$FILE_PATH" == */node_modules/* ]] || [[ "$FILE_PATH" == */node_modules ]]; then
  echo '{"decision": "block", "reason": "node_modules/ should never be edited directly."}'
  exit 0
fi

exit 0
