"""Systemd service management for Eventum."""

import shutil
import subprocess
import sys
import textwrap
from dataclasses import dataclass
from pathlib import Path

import yaml

SERVICE_NAME = 'eventum'

UNIT_TEMPLATE = textwrap.dedent("""\
    [Unit]
    Description=Eventum - Data generation platform
    Documentation=https://eventum.run/docs
    After=network.target

    [Service]
    Type=simple
    ExecStart={binary_path} run -c {config_path}
    ExecReload=/bin/kill -HUP $MAINPID
    Restart=on-failure
    RestartSec=5
    SuccessExitStatus=1
    StandardOutput=journal
    StandardError=journal
    SyslogIdentifier=eventum

    [Install]
    WantedBy={wanted_by}
""")

CONFIG_HEADER = (
    '# Eventum Configuration\n'
    '# Generated by: eventum service install\n'
    '# Full reference: https://eventum.run/docs/configuration\n'
    '\n'
)

STARTUP_CONTENT = (
    '# Generators to run at startup\n'
    '# See: https://eventum.run/docs/configuration\n'
    '[]\n'
)


class ServiceError(Exception):
    """Base exception for service management errors."""


class ServiceAlreadyInstalledError(ServiceError):
    """Service is already installed."""


class SystemdNotAvailableError(ServiceError):
    """systemd is not available on this system."""


class BinaryNotFoundError(ServiceError):
    """Eventum binary not found."""


@dataclass(frozen=True)
class ServicePaths:
    """Resolved paths for the service installation."""

    config_dir: Path
    log_dir: Path
    generators_dir: Path
    config_file: Path
    startup_file: Path
    cryptfile: Path
    unit_file: Path
    user_mode: bool


@dataclass(frozen=True)
class ServiceStatus:
    """Current state of the service."""

    installed: bool
    active: bool
    enabled: bool
    unit_file: Path | None
    config_file: Path | None
    user_mode: bool


class ServiceManager:
    """Manages the Eventum systemd service lifecycle."""

    def __init__(self, *, user_mode: bool) -> None:
        """Initialize service manager.

        Parameters
        ----------
        user_mode : bool
            Whether to manage a user-level systemd service.

        """
        self._user_mode = user_mode
        self._check_platform()
        self._check_systemd()

    def _unit_file_path(self) -> Path:
        """Compute the expected unit file path."""
        if self._user_mode:
            unit_dir = (
                Path.home() / '.config' / 'systemd' / 'user'
            )
        else:
            unit_dir = Path('/etc/systemd/system')

        return unit_dir / f'{SERVICE_NAME}.service'

    def resolve_paths(
        self,
        config_dir: Path,
        log_dir: Path,
    ) -> ServicePaths:
        """Build all derived paths from user-provided directories."""
        config_dir = config_dir.resolve()
        log_dir = log_dir.resolve()

        return ServicePaths(
            config_dir=config_dir,
            log_dir=log_dir,
            generators_dir=config_dir / 'generators',
            config_file=config_dir / 'eventum.yml',
            startup_file=config_dir / 'startup.yml',
            cryptfile=config_dir / 'cryptfile.cfg',
            unit_file=self._unit_file_path(),
            user_mode=self._user_mode,
        )

    @staticmethod
    def detect_binary() -> Path:
        """Find the eventum binary path."""
        binary = shutil.which('eventum')
        if binary is not None:
            return Path(binary).resolve()

        venv_bin = Path(sys.executable).parent / 'eventum'
        if venv_bin.is_file():
            return venv_bin.resolve()

        msg = (
            'Could not find eventum binary. '
            'Ensure eventum is installed and on PATH.'
        )
        raise BinaryNotFoundError(msg)

    def create_directories(self, paths: ServicePaths) -> list[Path]:
        """Create directories for the service.

        Returns
        -------
        list[Path]
            List of directories that were created.

        """
        created: list[Path] = []

        dirs = (paths.config_dir, paths.generators_dir, paths.log_dir)
        for directory in dirs:
            if not directory.exists():
                directory.mkdir(parents=True, exist_ok=True)
                created.append(directory)

        return created

    def generate_config(self, paths: ServicePaths) -> bool:
        """Write default eventum.yml.

        Returns
        -------
        bool
            True if generated, False if file already exists.

        """
        if paths.config_file.exists():
            return False

        config = self._build_config_dict(paths)

        with paths.config_file.open('w') as f:
            f.write(CONFIG_HEADER)
            yaml.dump(
                config, f, default_flow_style=False, sort_keys=False,
            )

        return True

    def generate_startup(self, paths: ServicePaths) -> bool:
        """Write empty startup.yml.

        Returns
        -------
        bool
            True if generated, False if file already exists.

        """
        if paths.startup_file.exists():
            return False

        paths.startup_file.write_text(STARTUP_CONTENT)
        return True

    def create_cryptfile(self, paths: ServicePaths) -> bool:
        """Create empty cryptfile.

        Returns
        -------
        bool
            True if created, False if file already exists.

        """
        if paths.cryptfile.exists():
            return False

        paths.cryptfile.touch()
        return True

    def generate_unit_content(
        self,
        paths: ServicePaths,
        binary_path: Path,
    ) -> str:
        """Render the systemd unit file content."""
        wanted_by = (
            'default.target'
            if self._user_mode
            else 'multi-user.target'
        )

        return UNIT_TEMPLATE.format(
            binary_path=binary_path,
            config_path=paths.config_file,
            wanted_by=wanted_by,
        )

    def install_unit(
        self,
        paths: ServicePaths,
        content: str,
    ) -> None:
        """Write unit file and reload systemd daemon."""
        if paths.unit_file.exists():
            msg = (
                f'Service already installed at {paths.unit_file}. '
                'Run `eventum service uninstall` first.'
            )
            raise ServiceAlreadyInstalledError(msg)

        paths.unit_file.parent.mkdir(parents=True, exist_ok=True)
        paths.unit_file.write_text(content)

        self._daemon_reload()

    def stop_service(self) -> None:
        """Stop the service (ignores errors if not running)."""
        self._systemctl('stop', SERVICE_NAME, check=False)

    def disable_service(self) -> None:
        """Disable the service (ignores errors if not enabled)."""
        self._systemctl('disable', SERVICE_NAME, check=False)

    def remove_unit(self, unit_file: Path) -> None:
        """Remove unit file and reload daemon."""
        unit_file.unlink()
        self._daemon_reload()

    def purge_directory(self, directory: Path) -> None:
        """Remove directory and all its contents."""
        if directory.exists():
            shutil.rmtree(directory)

    def get_status(self) -> ServiceStatus:
        """Query systemd for current service state."""
        unit_file = self._find_unit_file()

        if unit_file is None:
            return ServiceStatus(
                installed=False,
                active=False,
                enabled=False,
                unit_file=None,
                config_file=None,
                user_mode=self._user_mode,
            )

        active = self._is_active()
        enabled = self._is_enabled()
        config_file = self._extract_config_path(unit_file)

        return ServiceStatus(
            installed=True,
            active=active,
            enabled=enabled,
            unit_file=unit_file,
            config_file=config_file,
            user_mode=self._user_mode,
        )

    @staticmethod
    def _build_config_dict(paths: ServicePaths) -> dict:
        """Build the config dict for eventum.yml."""
        return {
            'server.ui_enabled': True,
            'server.api_enabled': True,
            'server.host': '0.0.0.0',  # noqa: S104
            'server.port': 9474,
            'server.auth.user': 'eventum',
            'server.auth.password': 'eventum',
            'generation.timezone': 'UTC',
            'log.level': 'info',
            'log.format': 'plain',
            'path.logs': str(paths.log_dir),
            'path.startup': str(paths.startup_file),
            'path.generators_dir': str(paths.generators_dir),
            'path.keyring_cryptfile': str(paths.cryptfile),
        }

    def _systemctl(
        self,
        *args: str,
        check: bool = True,
    ) -> subprocess.CompletedProcess[str]:
        """Run systemctl with --user flag if user_mode."""
        cmd = ['systemctl']
        if self._user_mode:
            cmd.append('--user')

        cmd.extend(args)

        return subprocess.run(  # noqa: S603
            cmd,
            capture_output=True,
            text=True,
            check=check,
        )

    def _daemon_reload(self) -> None:
        """Run systemctl daemon-reload."""
        self._systemctl('daemon-reload')

    def _find_unit_file(self) -> Path | None:
        """Find the installed unit file path."""
        unit_file = self._unit_file_path()
        return unit_file if unit_file.exists() else None

    def _is_active(self) -> bool:
        """Check if the service is active (running)."""
        result = self._systemctl(
            'is-active', SERVICE_NAME, check=False,
        )
        return result.stdout.strip() == 'active'

    def _is_enabled(self) -> bool:
        """Check if the service is enabled."""
        result = self._systemctl(
            'is-enabled', SERVICE_NAME, check=False,
        )
        return result.stdout.strip() == 'enabled'

    @staticmethod
    def _extract_config_path(unit_file: Path) -> Path | None:
        """Extract config path from ExecStart in unit file."""
        content = unit_file.read_text()
        for raw_line in content.splitlines():
            stripped = raw_line.strip()
            if stripped.startswith('ExecStart='):
                parts = stripped.split()
                for i, part in enumerate(parts):
                    if part == '-c' and i + 1 < len(parts):
                        return Path(parts[i + 1])
        return None

    @staticmethod
    def _check_platform() -> None:
        """Verify we are on Linux."""
        if sys.platform != 'linux':
            msg = 'Service management is only supported on Linux.'
            raise ServiceError(msg)

    @staticmethod
    def _check_systemd() -> None:
        """Verify systemctl is available."""
        if shutil.which('systemctl') is None:
            msg = 'systemd is not available on this system.'
            raise SystemdNotAvailableError(msg)
