"""Utils for aggregation of timestamps generated by input plugins."""

from datetime import timedelta

from eventum.api.routers.preview.models import AggregatedTimestamps
from eventum.core.preview import TimestampsAggregate, aggregate
from eventum.plugins.input.protocols import IdentifiedTimestamps


def aggregate_timestamps(
    timestamps: IdentifiedTimestamps,
    span: timedelta | None,
) -> AggregatedTimestamps:
    """Aggregate timestamps by fixed aligned time spans and plugins ids.

    Parameters
    ----------
    timestamps : IdentifiedTimestamps
        Record array of timestamps and input plugin ids.

    span : timedelta | None
        Span duration. In case `None` is provided auto span is used.

    Returns
    -------
    AggregatedTimestamps
        Aggregated timestamps.

    """
    agg: TimestampsAggregate = aggregate(timestamps, span)

    return AggregatedTimestamps(
        span_edges=agg.span_edges,
        span_counts=agg.span_counts,
        total=agg.total,
        first_timestamps=agg.first,
        last_timestamps=agg.last,
        timestamps=agg.timestamps,
    )
