export const ROUTE_PATHS = {
  SIGNIN: '/signin',
  ROOT: '/',
  MONITORING: '/monitoring',
  INSTANCES: '/instances',
  INSTANCE: '/instances/:instanceId',
  PROJECTS: '/projects',
  PROJECT: '/projects/:projectName',
  REPOSITORIES: '/repositories',
  SCENARIOS: '/scenarios',
  SCENARIO: '/scenarios/:scenarioName',
  SECRETS: '/secrets',
  SETTINGS: '/settings',
  MANAGEMENT: '/management',
  NOT_FOUND: '/404',
};
